/*
* generated by Xtext
*/
package org.applause.pbxproj.lang.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class PbxprojOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
