/*
 * generated by Xtext
 */
package org.applause.pbxproj.lang;

import org.applause.pbxproj.lang.naming.PbxprojQualifiedNameProvider;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class PbxprojRuntimeModule extends org.applause.pbxproj.lang.AbstractPbxprojRuntimeModule {

	@Override
	public Class<? extends org.eclipse.xtext.naming.IQualifiedNameProvider> bindIQualifiedNameProvider() {
		return PbxprojQualifiedNameProvider.class;
	}

}
