/*
* generated by Xtext
*/
package org.applause.pbxproj.lang.ui.contentassist;

import org.applause.pbxproj.lang.ui.contentassist.AbstractPbxprojProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class PbxprojProposalProvider extends AbstractPbxprojProposalProvider {

}
