/*
 * generated by Xtext
 */
package org.applause.pbxproj.lang.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class PbxprojUiModule extends org.applause.pbxproj.lang.ui.AbstractPbxprojUiModule {
	public PbxprojUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
